name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'version'
        required: true
        default: '0.1.0'
        
env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: pangliang
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build-push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: |
            pangliang/gitea-act-runner:v${{ inputs.VERSION }}
